# Generated by Django 6.0.3 on 2026-03-10 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('KITCHEN', 'Kitchen'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('VEHICLE', 'Vehicle'), ('OUTDOOR', 'Outdoor'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('model_number', models.CharField(blank=True, default='', max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('recurrence_type', models.CharField(choices=[('EVERY_N_DAYS', 'Every N days'), ('EVERY_N_WEEKS', 'Every N weeks'), ('EVERY_N_MONTHS', 'Every N months'), ('EVERY_N_YEARS', 'Every N years')], max_length=20)),
                ('interval', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('due_strategy', models.CharField(choices=[('FROM_START_DATE', 'From start date'), ('FROM_LAST_COMPLETION', 'From last completion')], max_length=30)),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='maintenance.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performed_by', models.CharField(blank=True, default='', max_length=200)),
                ('attachment_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='maintenance.maintenancetask')),
            ],
            options={
                'ordering': ['-completed_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'is_archived', 'category'], name='maintenance_user_id_07c8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'created_at'], name='maintenance_user_id_3870ef_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['user', 'is_archived', 'is_active', 'next_due_date'], name='maintenance_user_id_dcba9b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['user', 'created_at'], name='maintenance_user_id_d602e8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['user', 'completed_date'], name='maintenance_user_id_1c1332_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['task', 'completed_date'], name='maintenance_task_id_a15772_idx'),
        ),
    ]
