# Generated by Django 6.0.3 on 2026-03-14 14:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tracker_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=300)),
                ('job_url', models.URLField(blank=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='CAD', max_length=3)),
                ('location_type', models.CharField(blank=True, choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('status', models.CharField(choices=[('WISHLIST', 'Wishlist'), ('APPLIED', 'Applied'), ('PHONE_SCREEN', 'Phone Screen'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('GHOSTED', 'Ghosted')], default='WISHLIST', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source', models.CharField(blank=True, max_length=200)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tracker_applications', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_tracker.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role_at_company', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='job_tracker.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tracker_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='job_tracker.application')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.contact')),
            ],
            options={
                'ordering': ['contact__name'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPrepNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('COMPANY_RESEARCH', 'Company Research'), ('ROLE_NOTES', 'Role Notes'), ('QUESTIONS_TO_ASK', 'Questions to Ask'), ('TECH_PREP', 'Tech Prep'), ('BEHAVIORAL', 'Behavioral'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_notes', to='job_tracker.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tracker_prep_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='job_tracker.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tracker_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('NOTE', 'Note'), ('APPLIED', 'Applied'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_RECEIVED', 'Email Received'), ('PHONE_CALL', 'Phone Call'), ('INTERVIEW', 'Interview'), ('FOLLOW_UP', 'Follow Up'), ('OFFER', 'Offer'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tracker_activities', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='job_tracker.application')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['application', '-activity_date'], name='job_tracker_applica_ca6845_idx'), models.Index(fields=['user', '-created_at'], name='job_tracker_user_id_16e27a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'name'], name='job_tracker_user_id_5497f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_company_per_user'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='job_tracker_user_id_995934_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', '-created_at'], name='job_tracker_user_id_adb4de_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user', 'company'], name='job_tracker_user_id_0b1c2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationcontact',
            unique_together={('application', 'contact')},
        ),
        migrations.AddIndex(
            model_name='interviewprepnote',
            index=models.Index(fields=['application', 'category'], name='job_tracker_applica_19ccd5_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewprepnote',
            index=models.Index(fields=['user', '-updated_at'], name='job_tracker_user_id_a234fb_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'is_completed', 'reminder_date'], name='job_tracker_user_id_d29826_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', '-reminder_date'], name='job_tracker_user_id_dc7fc4_idx'),
        ),
    ]
