# Generated by Django 6.0.3 on 2026-03-12 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('APPLIANCE', 'Appliance'), ('ELECTRONICS', 'Electronics'), ('COMPUTER', 'Computer'), ('PHONE_TABLET', 'Phone/Tablet'), ('TOOL', 'Tool'), ('FURNITURE', 'Furniture'), ('VEHICLE', 'Vehicle'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DISCARDED', 'Discarded')], default='ACTIVE', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('URL', 'URL'), ('FILE', 'File')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='inventory_attachments/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('event_type', models.CharField(blank=True, choices=[('REPAIR', 'Repair'), ('MAINTENANCE', 'Maintenance'), ('INSTALL', 'Install'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_events', to='inventory.item')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('warranty_type', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('EXTENDED', 'Extended'), ('STORE', 'Store'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField(blank=True)),
                ('claim_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='inventory.item')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user', 'is_archived'], name='inventory_l_user_id_d68375_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'status', 'is_archived'], name='inventory_i_user_id_936f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', '-created_at'], name='inventory_i_user_id_e9b825_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceevent',
            index=models.Index(fields=['item', '-occurred_at'], name='inventory_s_item_id_77f09d_idx'),
        ),
        migrations.AddIndex(
            model_name='warranty',
            index=models.Index(fields=['item', 'end_date'], name='inventory_w_item_id_259ca2_idx'),
        ),
    ]
