# Generated by Django 6.0.3 on 2026-03-10 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=10)),
                ('weekly_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='primary-500', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_archived', 'is_active'], name='habits_habi_user_id_8f9560_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'created_at'], name='habits_habi_user_id_8aac28_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['user', 'date'], name='habits_habi_user_id_ba8925_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_e5e773_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcheckin',
            index=models.Index(fields=['user', 'habit'], name='habits_habi_user_id_72e221_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitcheckin',
            unique_together={('habit', 'date')},
        ),
    ]
