# Generated by Django 6.0.3 on 2026-03-13 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('url_normalized', models.CharField(db_index=True, max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('hostname', models.CharField(blank=True, db_index=True, max_length=255)),
                ('favicon_url', models.URLField(blank=True, max_length=2000)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('preview_image_url', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='links.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('READING', 'Reading'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='QUEUED', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='links.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'due_date', '-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_normalized', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g. #FF5733)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LinkTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_items', to='links.link')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_items', to='links.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'name'], name='links_colle_user_id_bc05d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_collection'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['user', '-created_at'], name='links_link_user_id_8efeff_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['user', 'url_normalized'], name='links_link_user_id_9e3b99_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['user', 'hostname'], name='links_link_user_id_29d784_idx'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('user', 'url_normalized'), name='unique_user_link'),
        ),
        migrations.AddIndex(
            model_name='readingqueueitem',
            index=models.Index(fields=['user', 'status'], name='links_readi_user_id_a26ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='readingqueueitem',
            index=models.Index(fields=['user', '-priority'], name='links_readi_user_id_3fbb19_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name_normalized'], name='links_tag_user_id_541a6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name_normalized'), name='unique_user_tag'),
        ),
        migrations.AddConstraint(
            model_name='linktag',
            constraint=models.UniqueConstraint(fields=('link', 'tag'), name='unique_link_tag'),
        ),
    ]
